# Generated by Django 4.0.3 on 2022-07-02 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=28)),
                ('cgst', models.FloatField(default=0.0)),
                ('sgst', models.FloatField(default=0.0)),
                ('igst', models.FloatField(default=0.0)),
                ('date', models.DateField()),
                ('total_amount', models.FloatField()),
                ('gst_without', models.FloatField()),
                ('round_off', models.FloatField()),
                ('time', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst_no', models.CharField(max_length=17)),
                ('state', models.CharField(max_length=30)),
                ('party_name', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('phone_no', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('hsn_code', models.CharField(max_length=8)),
                ('per', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSelling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, null=True)),
                ('qty', models.IntegerField()),
                ('rate', models.IntegerField(default=0)),
                ('billDetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.billdetails')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.product')),
            ],
        ),
        migrations.AddField(
            model_name='billdetails',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.partydetails'),
        ),
    ]
