# Generated by Django 4.0.3 on 2022-07-09 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_billdetails_cash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billdetails',
            name='cash',
        ),
        migrations.CreateModel(
            name='Payment_by',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payament_mode', models.CharField(choices=[('Cash', 'CASH'), ('Chaque', 'CHEQUE'), ('UPI', 'UPI'), ('NEFT', 'NEFT'), ('Other', 'OTHER')], default='Cash', max_length=7)),
                ('pay', models.FloatField(default=0.0)),
                ('billDetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.billdetails')),
            ],
        ),
    ]
