# Generated by Django 4.0.3 on 2022-07-12 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_alter_billdetails_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_by',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productselling',
            name='choice',
            field=models.CharField(choices=[('1', 'Selling'), ('2', 'Purchasing')], default='2', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='payment_by',
            name='billDetails',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.billdetails'),
        ),
        migrations.AlterField(
            model_name='payment_by',
            name='pay',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='productselling',
            name='billDetails',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.billdetails'),
        ),
        migrations.CreateModel(
            name='PurchaseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgst', models.FloatField(default=0.0, null=True)),
                ('sgst', models.FloatField(default=0.0, null=True)),
                ('igst', models.FloatField(default=0.0, null=True)),
                ('date', models.DateField(null=True)),
                ('total_amount', models.FloatField(default=0.0, null=True)),
                ('gst_without', models.FloatField(null=True)),
                ('round_off', models.FloatField(null=True)),
                ('time', models.TimeField(auto_now=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.partydetails')),
            ],
        ),
        migrations.AddField(
            model_name='payment_by',
            name='purchaseDetail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.purchasedetails'),
        ),
        migrations.AddField(
            model_name='productselling',
            name='purchaseDetails',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.purchasedetails'),
        ),
    ]
