# Generated by Django 4.0.3 on 2022-07-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_payment_by_date_productselling_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_by',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payment_by',
            name='pay',
            field=models.FloatField(null=True),
        ),
    ]
