# Generated by Django 4.0.3 on 2022-10-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_alter_payment_by_billdetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productselling',
            name='qty',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
