# Generated by Django 4.0.3 on 2023-02-28 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_alter_productselling_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partydetails',
            name='gst_no',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
