# Generated by Django 4.0.3 on 2025-04-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_alter_partydetails_gst_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partydetails',
            name='party_name',
            field=models.CharField(max_length=60),
        ),
    ]
